distributed.nanny - INFO -         Start Nanny at: 'tcp://10.10.15.9:39854'
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-32sivcv1', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-ga0xx30q', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-oxi861m2', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-mkvc6okl', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-e5_68xz3', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-qy1wx7vd', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-iyrbgzp_', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-6m_cxeiu', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-83izmjcr', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-v_zw83g7', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-ibfct5d0', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-zko06gs4', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-n4c9uc7p', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-6p9y7ijx', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-oajsdyn8', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-5urlt7z2', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-68xnp3oy', purging
distributed.worker - INFO -       Start worker at:     tcp://10.10.15.9:34980
distributed.worker - INFO -          Listening to:     tcp://10.10.15.9:34980
distributed.worker - INFO -          dashboard at:           10.10.15.9:46880
distributed.worker - INFO - Waiting to connect to:    tcp://10.10.15.13:41641
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    2.00 GB
distributed.worker - INFO -       Local Directory: /users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-bi7e3_cy
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Waiting to connect to:    tcp://10.10.15.13:41641
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.9:45226 remote=tcp://10.10.15.13:41641>
distributed.worker - INFO - Waiting to connect to:    tcp://10.10.15.13:41641
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.9:45238 remote=tcp://10.10.15.13:41641>
distributed.worker - INFO - Waiting to connect to:    tcp://10.10.15.13:41641
distributed.worker - INFO - Waiting to connect to:    tcp://10.10.15.13:41641
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.9:45290 remote=tcp://10.10.15.13:41641>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.9:45294 remote=tcp://10.10.15.13:41641>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.9:45300 remote=tcp://10.10.15.13:41641>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.9:45304 remote=tcp://10.10.15.13:41641>
distributed.worker - INFO - Waiting to connect to:    tcp://10.10.15.13:41641
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.9:45306 remote=tcp://10.10.15.13:41641>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.9:45314 remote=tcp://10.10.15.13:41641>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.9:45316 remote=tcp://10.10.15.13:41641>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.9:45324 remote=tcp://10.10.15.13:41641>
distributed.nanny - INFO - Closing Nanny at 'tcp://10.10.15.9:39854'
distributed.worker - INFO - Stopping worker at tcp://10.10.15.9:34980
distributed.worker - INFO - Closed worker has not yet started: Status.undefined
distributed.dask_worker - INFO - End worker
Traceback (most recent call last):
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/distributed/core.py", line 295, in _
    await asyncio.wait_for(self.start(), timeout=timeout)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/distributed/cli/dask_worker.py", line 460, in <module>
    go()
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/distributed/cli/dask_worker.py", line 456, in go
    main()
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/distributed/cli/dask_worker.py", line 442, in main
    loop.run_sync(run)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/tornado/ioloop.py", line 532, in run_sync
    return future_cell[0].result()
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/distributed/cli/dask_worker.py", line 436, in run
    await asyncio.gather(*nannies)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/asyncio/tasks.py", line 684, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/distributed/core.py", line 299, in _
    raise TimeoutError(
asyncio.exceptions.TimeoutError: Nanny failed to start in 60 seconds
