41
subject 143325
loaded saved variables
version 3
105
/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/distributed/node.py:151: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 37147 instead
  warnings.warn(
parrallel submitted 09:01:38
parrallel finished 09:05:52
estimation_imag_fix_testretest.py:217: ComplexWarning: Casting complex values to real discards the imaginary part
  inv_JinvCeJ[i,:] = J[:,i].T * inv_DiagCe
estimation_imag_fix_testretest.py:230: ComplexWarning: Casting complex values to real discards the imaginary part
  P[:,i] = (J[:,i]*np.squeeze(inv_DiagCe))
estimation_imag_fix_testretest.py:250: ComplexWarning: Casting complex values to real discards the imaginary part
  g[i] = -0.5*np.exp(lembda[i])*np.trace(P[T*i:T*i+T][:, T*i:T*i+T])
estimation_imag_fix_testretest.py:255: ComplexWarning: Casting complex values to real discards the imaginary part
  g[i] = g[i] + g_rest
/users/k1201869/wang_model/code/model_fitting/wang_functions_imag_fix.py:502: ComplexWarning: Casting complex values to real discards the imaginary part
  tr[i] = np.sum(temp)
/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/numpy/core/fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
[[-2.07210633]]
estimation_imag_fix_testretest.py:309: ComplexWarning: Casting complex values to real discards the imaginary part
  JinvCe[i,:] = J[:,i] * inv_DiagCe #;% J'%invCe <----- p x nT
estimation_imag_fix_testretest.py:320: ComplexWarning: Casting complex values to real discards the imaginary part
  A_FDK[:,ppi] = np.squeeze(A) + np.squeeze(d_A) # %newton-gauss, fisher scoring, update Para_E
/users/k1201869/wang_model/code/model_fitting/wang_functions_imag_fix.py:517: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  sol = np.linalg.lstsq(A, b)[0]    # not under-determined
estimation_imag_fix_testretest.py:327: ComplexWarning: Casting complex values to real discards the imaginary part
  A_FDK[:,ppi] = np.squeeze(A) + d_A #newton-gauss, fisher scoring, update Para_E
distributed.client - ERROR - Failed to reconnect to scheduler after 10.00 seconds, closing client
_GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=CancelledError()>
asyncio.exceptions.CancelledError
estimation_imag_fix_testretest.py:331: ComplexWarning: Casting complex values to real discards the imaginary part
  h_output_FDK[:,ppi], CC_check_FDK[ppi] = funcP(np.atleast_2d(Para_E_new).T)
estimation_imag_fix_testretest.py:334: ComplexWarning: Casting complex values to real discards the imaginary part
  dlddpara_FDK[:,:,ppi] = dlddpara
estimation_imag_fix_testretest.py:335: ComplexWarning: Casting complex values to real discards the imaginary part
  dldpara_FDK[:,ppi] = dldpara
[[-2.01005336]]
imaginary won
goodness of fit correlation [0.12041989]
0.350107804360889
[5.31998039e-01 5.17233452e-01 4.93477858e-01 5.06248369e-01
 5.10366009e-01 5.62090284e-01 5.99017542e-01 5.57245938e-01
 5.12911430e-01 5.35027052e-01 5.10450739e-01 5.40841306e-01
 5.14576619e-01 5.71572874e-01 5.12316925e-01 4.98511753e-01
 4.97942573e-01 5.17606091e-01 5.37985297e-01 5.32447026e-01
 5.11644126e-01 5.31832125e-01 4.83036861e-01 5.23393495e-01
 5.06464781e-01 5.05398028e-01 4.95406602e-01 5.60928006e-01
 5.35012692e-01 5.67090850e-01 5.08763805e-01 5.07798348e-01
 5.09796326e-01 5.08702751e-01 5.07125360e-01 5.16556835e-01
 5.12627759e-01 5.11424084e-01 5.07789615e-01 5.44877370e-01
 5.57832993e-01 5.34328081e-01 4.94182195e-01 5.17483785e-01
 5.33365733e-01 5.17454182e-01 5.26335505e-01 5.29841828e-01
 5.27778554e-01 5.10819266e-01 5.15769729e-01 5.21282300e-01
 5.10503120e-01 5.31528239e-01 5.73536431e-01 5.59472625e-01
 5.00991353e-01 5.19175134e-01 5.12869952e-01 4.97199077e-01
 4.80941187e-01 5.31612444e-01 5.38277515e-01 5.82554724e-01
 5.14125085e-01 5.28753367e-01 5.17016961e-01 5.72074419e-01
 3.48455647e-01 3.34218719e-01 3.39813772e-01 3.45798199e-01
 3.34955179e-01 3.42494666e-01 3.29433543e-01 3.39147305e-01
 3.32497505e-01 3.45776854e-01 3.39065701e-01 3.33810820e-01
 3.48020454e-01 3.37627195e-01 3.42256251e-01 3.37097177e-01
 3.36176185e-01 3.40211470e-01 3.34865688e-01 3.39236010e-01
 3.38966651e-01 3.41657933e-01 3.40636936e-01 3.42792212e-01
 3.21561997e-01 3.49007365e-01 3.15317378e-01 3.31212746e-01
 3.38095940e-01 3.40197420e-01 3.42587160e-01 3.27878707e-01
 3.42435796e-01 3.30200782e-01 3.53489485e-01 3.38443551e-01
 3.21372652e-01 3.54867966e-01 3.26644302e-01 3.46337777e-01
 3.33115933e-01 3.35851128e-01 3.31171552e-01 3.27557998e-01
 3.40775815e-01 3.27273252e-01 3.40992505e-01 3.36792786e-01
 3.39088971e-01 3.46257315e-01 3.50143939e-01 3.45773621e-01
 3.41986091e-01 3.61475505e-01 3.38097131e-01 3.38986133e-01
 3.43266519e-01 3.40957219e-01 3.35614722e-01 3.49330090e-01
 3.17313747e-01 3.36541585e-01 3.51171619e-01 3.44687404e-01
 3.33379231e-01 3.41143021e-01 3.38390568e-01 3.28596266e-01
 1.59655224e+00 1.00497520e-03]
version 4
0
/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/distributed/node.py:151: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 35094 instead
  warnings.warn(
parrallel submitted 09:06:39
